# fly.toml app configuration file generated for warmup-project on 2025-10-16T08:16:40-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'warmup-project'
primary_region = 'lax'

[build]
  dockerfile = "Dockerfile"

[[mounts]]
  source = "ollama_data"
  destination = "/root/.ollama"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = "30s"
    timeout = "3s"
    grace_period = "15s"
    method = "GET"
    path = "/healthz"

