blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/CSE210-fa25-team09/Warmup-Project/discussions
    about: For questions or discussions, please use GitHub Discussions
